Completed css-brochure-form Exercise. -Anna Park
annuhpark/c0122-code-solutions pull request #16
Opened 2022-01-27 06:35 UTC by annuhpark

<img width="784" alt="Screen Shot 2022-01-26 at 10 29 47 PM" src="https://user-images.githubusercontent.com/69396309/151304791-c4ea3200-e8e1-45d6-9615-a45fec28cdd6.png">

2022-01-27 18:18 UTC, codingcodymiller requested changes
Hey Anna! Your submit button is indented a bit too much from the right side of the form as compared to the example, please revise and submit a new screenshot with your revision.

2022-01-28 19:38 UTC, annuhpark commented
<img width="688" alt="Screen Shot 2022-01-28 at 11 38 00 AM" src="https://user-images.githubusercontent.com/69396309/151610639-693ffa3a-4ee4-44b2-b53a-1cbdf05986bb.png">

2022-01-28 19:52 UTC, codingcodymiller requested changes

2022-01-28 19:52 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +}
You have three individual rules applied to `id`s with the exact same declaration block. Instead of using `id`s for your styling, you should add a class to each of those elements, and make one rule for that class.

2022-01-28 23:13 UTC, codingcodymiller requested changes

2022-01-28 23:13 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +}
This is still multiple different rules with the same styling. You should make **_one_** class, and apply that same class to all three elements.

2022-01-31 17:28 UTC, codingcodymiller approved these changes

2022-02-09 21:06 UTC, merged