Completed css-two-column-layout Exercise. -Anna Park
annuhpark/c0122-code-solutions pull request #21
Opened 2022-01-29 23:57 UTC by annuhpark

<img width="958" alt="Screen Shot 2022-01-29 at 3 53 27 PM" src="https://user-images.githubusercontent.com/69396309/151681565-3775d00d-1dcd-49fa-b493-7a86877d7a6f.png">

2022-01-31 18:21 UTC, codingcodymiller requested changes
Hey Anna! I see that you have a `container` and a `row` class, but you are missing any `column` classes. I suggest you review the `css-layout-classes` exercise, then revise your classes and HTML setup to follow proper layout classes protocol.

2022-02-04 18:29 UTC, codingcodymiller requested changes
You have a **_lot_** of negative values for margin and padding. You should try to avoid those as much as possible. In general, if you feel like you need to use a negative margin, you need to reduce the margin you have applied to sibling elements or increase the size of the elements you are trying to affect.

2022-02-05 05:21 UTC, annuhpark commented
<img width="665" alt="Screen Shot 2022-02-04 at 9 14 27 PM" src="https://user-images.githubusercontent.com/69396309/152629804-89236c29-a63a-464d-91ee-dabf83a0bdea.png">

2022-02-07 18:03 UTC, codingcodymiller approved these changes

2022-02-09 21:04 UTC, merged