Completed css-four-column-layout Exercise. -Anna Park
annuhpark/c0122-code-solutions pull request #30
Opened 2022-02-02 06:52 UTC by annuhpark

<img width="948" alt="Screen Shot 2022-02-01 at 10 49 00 PM" src="https://user-images.githubusercontent.com/69396309/152107293-54e148eb-ea2f-488f-9d3e-8ffab13d84ff.png">

2022-02-02 18:21 UTC, codingcodymiller requested changes

2022-02-02 18:21 UTC, codingcodymiller commented on css-four-column-layout/index.html
> +    </div>
I can see why you would do this from the perspective of layout classes, but by putting the images, icons, and text in separate rows, your HTML looks like this content is not related to one another. You should have one row with four columns, and each column contains the phone image, icon, and text all together.

2022-02-04 19:40 UTC, codingcodymiller requested changes

2022-02-04 19:40 UTC, codingcodymiller commented on css-four-column-layout/index.html
> +      <div class="row flex-direction-column column-one-fourth
No one element should be both a `row` and a `column`. You should make an element that is a child of this `column` class element with the class `row` and put the content of this `column` inside that `row` element.

2022-02-05 04:44 UTC, annuhpark commented
<img width="1036" alt="Screen Shot 2022-02-04 at 8 42 30 PM" src="https://user-images.githubusercontent.com/69396309/152628988-7eeb2873-d7f2-42e4-83a1-1ca50b92b3c7.png">

2022-02-09 21:12 UTC, merged