Completed css-ecommerce-page Exercise. -Anna Park
annuhpark/c0122-code-solutions pull request #38
Opened 2022-02-06 00:24 UTC by annuhpark

<img width="1049" alt="Screen Shot 2022-02-05 at 4 22 52 PM" src="https://user-images.githubusercontent.com/69396309/152663412-6ee7c2df-c135-4395-805e-70ee79238d42.png">

2022-02-07 18:17 UTC, codingcodymiller requested changes

2022-02-07 18:17 UTC, codingcodymiller commented on css-ecommerce-page/index.html
> +            <br>
No `br` elements, please

2022-02-07 18:17 UTC, codingcodymiller commented on css-ecommerce-page/index.html
> +        <div class="row flex-direction-column">
Why `flex-direction: column` here? There's a lot of content that needs to sit side-by-side in here, you would probably be better off just using `p` elements with `span` child elements for each chunk of text.

2022-02-09 04:43 UTC, annuhpark commented
<img width="1062" alt="Screen Shot 2022-02-08 at 8 42 24 PM" src="https://user-images.githubusercontent.com/69396309/153123335-9871ecfa-ff87-4e4a-8619-8df902f6079b.png">

2022-02-09 15:48 UTC, thebearingedge requested changes

2022-02-09 15:48 UTC, thebearingedge commented on css-ecommerce-page/index.html
> +    </div>
Please restructure your document so that each column has the image as well as the text instead of two separate rows.

2022-02-10 02:09 UTC, annuhpark commented
<img width="1086" alt="Screen Shot 2022-02-09 at 6 09 17 PM" src="https://user-images.githubusercontent.com/69396309/153323614-8b20a35c-b5e5-4a20-b649-1a833775c7dd.png">

2022-02-10 16:00 UTC, thebearingedge approved these changes

2022-02-10 20:07 UTC, merged